import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

export class PluginSDK {
  constructor(rootDir) {
    this.rootDir = rootDir;
  }

  async createPlugin(name, description, author) {
    const pluginDir = join(this.rootDir, `.cursor/plugins/${name}`);
    await mkdir(join(pluginDir, 'agents'), { recursive: true });
    await mkdir(join(pluginDir, 'rules'), { recursive: true });

    const manifest = {
      name,
      description,
      author,
      version: '1.0.0',
      installedAt: new Date().toISOString()
    };

    await writeFile(join(pluginDir, 'manifest.json'), JSON.stringify(manifest, null, 2));

    // Create a template agent
    const agentContent = `---
name: ${name}:specialist
description: Core specialist for ${name}.
parent: orchestrator
---
# ${name.toUpperCase()} Specialist
Generated by Cursor AI OS SDK.
`;
    await writeFile(join(pluginDir, 'agents', 'specialist.md'), agentContent);

    return { message: `Plugin ${name} created at ${pluginDir}` };
  }
}
